server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/products/**
              filters:
                - AddResponseHeader=X-Platform, microservices-pro

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - AddResponseHeader=X-Platform, microservices-pro

gateway:
  public-routes:
    - method: POST
      path: /api/auth/login
    - method: POST
      path: /api/auth/register
    - method: GET
      path: /actuator/**
    - method: GET
      path: /api/v1/products/**

jwt:
  secret: munamelafsafanflalss112377122dfasd

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info