apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: ecommerce
data:
  datasource.url: jdbc:postgresql://postgres:5432/productdb
  redis.host: redis
  eureka.url: http://eureka-server:8761/eureka/
