spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:https://github.com/husseineelsaka/Enterprise-E-Commerce-Platform-Config-Repo}
          default-label: ${SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL:main}
          clone-on-start: true

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health, info